platform:
    - x64

image: Visual Studio 2019

environment:

  matrix:
    #- PYTHON: "C:\\Python35-{platform}"
    #- PYTHON: "C:\\Python36-%PLATFORM%"
    #- PYTHON: "C:\\Python37-%PLATFORM%"
    - PYTHON: "C:\\Python38-%PLATFORM%"
    - PYTHON: "C:\\Python39-%PLATFORM%"
    - PYTHON: "C:\\Python310-%PLATFORM%"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"

build: off

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*

deploy:
  release: pythran-openblas-v$(APPVEYOR_BUILD_VERSION)
  description: 'Wheel build for openblas on windows'
  provider: GitHub
  auth_token:
    secure: VUyxhdfJnyLLN0ZNv8DzHWa/5AaO0cRGQFaS/Z5xPTJQwAYRf0y4kq8ZSgSyBS7VIFmaGN1zpWpB5sZou2eoXnjm2XkUzIdp4d5EYtGCAVvmK6EudLjVdFtsdE8OvCWd
  artifact: dist\*whl            # upload all wheel files
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
